# Git repo token: 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
# Example Web Server pass: dX2xO2jF4iP9qB8nW6rJ9hY9sT1tR0xC
# Example DB Server pass: pG6zI0bS7jC2cL5zI6hS8fB5aJ3wT4dC

- hosts: localhost
  connection: local

  vars_prompt:
    - name: app_serv_pass
      prompt: "Enter the Web App server's administrator password"
    - name: db_serv_pass
      prompt: "Enter the DB server's administrator password"

  tasks: 
    - name: Create resource group 
      azure_rm_resourcegroup:
        name: endava-project-rg
        location: germanywestcentral

    # A virtual network is required for the VM setup. Otherwise we receive this error:
    # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: unable to find virtual network in resource group endava-project-rg. A virtual network with at least one subnet must exist in order to create a NIC for the virtual machine."}
    # Source: https://dev.to/cloudskills/deploying-resources-to-azure-with-ansible-1pon
    - name: Create a virtual network for the Python App VM 
      azure_rm_virtualnetwork:
        resource_group: endava-project-rg
        name: endava_vNet
        address_prefixes: "10.0.0.0/16"
        state: present

    - name: Add a Public IP Address
      azure_rm_publicipaddress:
        resource_group: endava-project-rg
        allocation_method: Static
        name: endava_project_pub_ip
        # Register allows you to populate variables based on the output of Ansible tasks.
      register: output_ip_address

    - name: Output public IP Address
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    # It seems a network security group is necessary to define the allowed ports and protocols
    # Source: https://dev.to/cloudskills/deploying-resources-to-azure-with-ansible-1pon
    # Source: https://medium.com/@pavithra_38952/building-infrastructure-with-microsoft-azure-and-ansible-e5245e5b33a8
    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: endava-project-rg
        name: networkSecurityGroup
        rules:
        - name: 'ssh' 
          protocol: Tcp 
          destination_port_range: 22 
          access: Allow
          priority: 100
          direction: Inbound 
        - name: 'http' 
          protocol: Tcp 
          destination_port_range: 80 
          access: Allow
          priority: 101 
          direction: Inbound 
        - name: 'https' 
          protocol: Tcp 
          destination_port_range: 443 
          access: Allow
          priority: 102 
          direction: Inbound 
        - name: 'py-webapp' 
          protocol: Tcp 
          destination_port_range: 3001
          access: Allow
          priority: 103 
          direction: Inbound 
            
   # Source: https://dev.to/cloudskills/deploying-resources-to-azure-with-ansible-1pon
    - name: Add a subnet for App server
      azure_rm_subnet:
        name: webSubnet2
        resource_group: endava-project-rg
        address_prefix: "10.0.0.0/24"
        virtual_network: endava_vNet
        #security_group_name: networkSecurityGroup
        state: present
      register: output_private_ip

    - name: Output private IP Address
      debug: 
        msg: "The private IP of the VM is {{ output_private_ip }}"

    # Source: https://dev.to/cloudskills/deploying-resources-to-azure-with-ansible-1pon
    # Source !!!!: https://docs.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible
    - name: Create a network interface for the web app VM
      azure_rm_networkinterface:
        name: webapp_netInterface
        resource_group: endava-project-rg
        virtual_network: endava_vNet
        subnet: webSubnet2
        security_group: networkSecurityGroup
        ip_configurations:
          - name: default
            public_ip_address_name: endava_project_pub_ip
            private_ip_address: output_private_ip.state.ip_address
            primary: True



    - name: Create VM for the Python App
      azure_rm_virtualmachine:
        resource_group: endava-project-rg
        # It seems that '_' characters can't be used in Linux hostnames on Azure:
        # Source: https://github.com/hashicorp/terraform-provider-azurerm/issues/280
        name: webapp-serv
        # Source: https://docs.microsoft.com/en-us/azure/virtual-machines/sizes
        # Source: https://portal.azure.com/#create/canonical.0001-com-ubuntu-server-focal20_04-lts-ARM
        vm_size: Standard_B1s
        admin_username: todor
        admin_password: "{{ app_serv_pass }}"
        open_ports: 
          - 22
          - 80
          - 443
          - 3001
        network_interfaces: webapp_netInterface
        # Source: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualmachine_module.html#ansible-collections-azure-azcollection-azure-rm-virtualmachine-module
        os_type: Linux
        # Source: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualmachine_module.html#examples
        image: 
          # Source: https://portal.azure.com/#create/canonical.0001-com-ubuntu-server-focal20_04-lts-ARM
          offer: debian-10
          publisher: Debian
          sku: '10'
          version: latest 


# MYSQL Section           
    # Source: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_mariadbserver_module.html
    # This task creates a MariaDB server 
    - name: Create MariaDB Server
      azure_rm_mariadbserver: 
        resource_group: endava-project-rg
        name: webapp-mariadb-server
        sku:
          name: B_Gen5_1
          tier: Basic  
        location: germanywestcentral
        storage_mb: 5120
        enforce_ssl: False
        version: 10.2
        admin_username: todor
        admin_password: "{{ db_serv_pass }}"
      register: fully_qualified_domain_name 

    - name: Print the URL of the MySQL server
      debug:
        msg: "The URL of the MySQL Host server is {{ fully_qualified_domain_name .state }}" 

    # Source: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_mariadbdatabase_module.html
    # And this task creates a DB for it to which we can later connect
    - name: Create MariaDB DB instance
      azure_rm_mariadbdatabase:
        resource_group: endava-project-rg
        server_name: webapp-mariadb-server
        name: webapp-mariadb-db


    # Source: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_mysqlfirewallrule_module.html
    - name: Allow external access to MySQL via a Firewall 
      azure_rm_mysqlfirewallrule:
        resource_group: endava-project-rg
        server_name: webapp-mariadb-server
        name: webapp-mariadb-firewall-allow
        start_ip_address: 0.0.0.0
        end_ip_address: 255.255.255.255

    # Code below may be deprecated 
    # Source: https://docs.microsoft.com/en-us/azure/developer/ansible/mysql-configure?tabs=ansible#configure-a-firewall-rule
    #  azure_rm_resource: 
    #    api_version: '2017-12-01'
    #    resource_group: endava-project-rg
    #    provider: dbformysql
    #    resource_type: servers
    #    resource_name: webapp-mariadb-server
    #    subresource: 
    #      - type: firewallrules
    #        name: externalaccess
    #    body:
    #      properties: 
    #        startIpAddress: "0.0.0.0"
    #        endIpAddress: "255.255.255.255"




