---
# Source: https://stackoverflow.com/questions/55472314/how-to-deploy-code-from-local-git-repository-to-remote-server-using-ansible
# Source: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
# Source: https://blog.knoldus.com/how-to-install-python-in-target-host-using-ansible/
- hosts: azure-app-vms
  connection: local
  become_method: su

  vars_prompt:
    - name: app_serv_pass
      prompt: "Enter the Web App server's administrator password"

  tasks:
    - name: Make temp directory
      tempfile:
        state: directory
      register: temp_git_archive
      delegate_to: localhost
      changed_when: False
    
    # Source: https://opensource.com/article/17/8/ansible-environment-management
    # The source above doesn't work because the SSH account is not root but has sudo permissions 
    # Therefore to solve this issue we need to run a command instead 
    - name: Installing git  on the target VM
      command: sudo apt-get install -y git

    - name: Installing pip3 on the target VM
      command: sudo apt-get install -y python3-pip

    # Source: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    - name: Clone the repo in specified directory 
      ansible.builtin.git:
        repo: https://github.com/TodorDimitrovIvanov/PythonWebApp/
        dest:  /home/todor/web

    # Source: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
    - name: Install Python requirements using pip
      pip: 
        executable: /usr/bin/pip3
        requirements: /var/www/html/requirements.txt

    # Source: https://stackoverflow.com/questions/35139711/running-python-script-via-ansible
    - name: Start the Python web app 
      script: app.py

